[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.20.3"